name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    # - name: Build
    #   run: cargo build --verbose

    # - name: Run tests
    #   run: cargo test --verbose

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: nutbodyslam053/myapp-rust
        tags: v99.0
        registry: docker.io
        multiPlatform: true
        platform: linux/amd64,linux/arm64,linux/arm/v7
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
