name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_VERSION: latest
      VERSION_COUNTER: 0

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Increment Version Counter
      run: echo "VERSION_COUNTER=$((VERSION_COUNTER+1))" >> $GITHUB_ENV
      shell: bash

    - name: Set Docker Image Version
      run: echo "DOCKER_IMAGE_VERSION=${{ env.VERSION_COUNTER }}.0" >> $GITHUB_ENV
      shell: bash

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: nutbodyslam053/myapp-rust
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: ${{ env.DOCKER_IMAGE_VERSION }}
